# Generated by Django 5.1.6 on 2025-05-02 13:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ou2gether', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_avatar',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='current_cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
