# Generated by Django 5.1.6 on 2025-05-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ou2gether', '0002_user_current_avatar_user_current_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='current_cover',
            new_name='cover',
        ),
    ]
