# Generated by Django 5.1.6 on 2025-05-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ou2gether', '0002_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_set_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Admin'), (1, 'Lecturer'), (2, 'Student')], default=2),
        ),
    ]
