# Generated by Django 5.1.6 on 2025-05-06 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ou2gether', '0003_user_is_locked_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_set_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 7, 8, 22, 29, 852110, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
