# Generated by Django 5.1.6 on 2025-05-06 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ou2gether', '0004_alter_user_password_set_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpoll',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 12, 51, 10, 608775, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password_set_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
