# Generated by Django 5.1.6 on 2025-05-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ou2gether', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='user',
            new_name='author',
        ),
    ]
