# Generated by Django 5.1.6 on 2025-05-03 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ou2gether', '0006_rename_user_comment_author_rename_user_share_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmedia',
            name='comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ou2gether.comment'),
        ),
    ]
