# Generated by Django 5.1.6 on 2025-05-03 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ou2gether', '0007_alter_commentmedia_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmedia',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_media', to='ou2gether.comment'),
        ),
    ]
