# Generated by Django 5.1.6 on 2025-05-03 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ou2gether', '0009_post_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmedia',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_media', to='ou2gether.comment'),
        ),
    ]
