# Generated by Django 5.1.6 on 2025-05-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ou2gether', '0010_alter_commentmedia_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpoll',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ou2gether.post'),
        ),
    ]
