# Generated by Django 5.1.6 on 2025-05-04 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ou2gether', '0011_alter_postpoll_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ou2gether.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentmedia',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ou2gether.comment'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='post_poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ou2gether.postpoll'),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='poll_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='ou2gether.polloption'),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ou2gether.post'),
        ),
        migrations.AlterField(
            model_name='postpoll',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='ou2gether.post'),
        ),
    ]
